VWORLD_API_KEY = "DE3A8930-9F45-342B-9329-751FB0EFBE98"
OPENWEATHER_API_KEY = "5c4ca9588909516155088222e0cad846"
ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjcxMmY1MDhkZDA1MTRiMzc4NGIwNjk5ZTc0ZTc2NDJiIiwiaCI6Im11cm11cjY0In0="
NAVER_CLIENT_ID = "9a6gnzM1fF7W31XYTCQI"
NAVER_CLIENT_SECRET = "2wU1ky3Y3O"
KAKAO_REST_KEY = "a3c9b70b8efa6f39800aa1f017e91237"
KAKAO_REST_API_KEY = "a3c9b70b8efa6f39800aa1f017e91237"
KAKAO_JS_KEY = ""
